main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('birds/', views.birds_index, name='index'),
    path('birds/<int:bird_id>/', views.birds_detail, name='detail'),
    path('birds/<int:bird_id>/add_feeding', views.add_feeding, name='add_feeding'),
    path('birds/<int:bird_id>/assoc_house/<int:house_id>/', views.assoc_house, name='assoc_house'),
    path('birds/create/', views.BirdCreate.as_view(), name='birds_create'),
    path('birds/<int:pk>/update/', views.BirdUpdate.as_view(), name='birds_update'),
    path('birds/<int:pk>/delete/', views.BirdDelete.as_view(), name='birds_delete'),
    
    path('birds/<int:bird_id>/add_photo/', views.add_photo, name='add_photo'),

    path('houses/', views.HouseList.as_view(), name='houses_index'),
    path('houses/<int:pk>/', views.HouseDetail.as_view(), name='houses_detail'),
    path('houses/create/', views.HouseCreate.as_view(), name='houses_create'),
    path('houses/<int:pk>/update/', views.HouseUpdate.as_view(), name='houses_update'),
    path('houses/<int:pk>/delete/', views.HouseDelete.as_view(), name='houses_delete'),
]

socalbirdcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse


# you can access the cat with cat_set when you have toy
class House(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('houses_detail', kwargs={'pk': self.id})

# Create your models here.
class Bird(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    houses = models.ManyToManyField(House)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'bird_id': self.id})
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for bird_id: {self.bird_id} @{self.url}"


# A tuple of 2-tuples
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)


class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
        )
    
    # Create a bird_id FK
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
# forms.py

from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
# main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from .models import Bird, House, Photo

from .forms import FeedingForm

import boto3
import uuid
import os

# Add this cats list below the imports
# birds = [
#   {'name': 'Novie', 'breed': 'turkey vulture', 'description': 'furry little demon', 'age': 3},
#   {'name': 'Woody', 'breed': 'acorn woodpecker', 'description': 'gentle and loving', 'age': 2},
# ]

def add_photo(request, bird_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = f"socalbirdcollector/{uuid.uuid4().hex[:6]}{photo_file.name[photo_file.name.rfind('.'):]}"
    try:
      bucket = os.environ['BUCKET_NAME']
			# upload to aws, file, bucket name, where you want to store it in bucket
      s3.upload_fileobj(photo_file, bucket, key)
			# build the url to save to the database
      photo_url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
			# save the url to the Photo Model
      Photo.objects.create(url=photo_url, bird_id=bird_id)

    except Exception as e:
      print('An error uploading to AWS')
      print(e)
  return redirect('detail', bird_id=bird_id)

class BirdCreate(CreateView):
  model = Bird
  fields = ['name', 'breed', 'description', 'age']

class BirdUpdate(UpdateView):
  model = Bird
  # Let's disallow the renaming of a Bird by excluding the name field!
  fields = ['breed', 'description', 'age']

class BirdDelete(DeleteView):
  model = Bird
  success_url = '/birds'


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

# Add new view
def birds_index(request):
  # We pass data to a template very much like we did in Express!
  birds = Bird.objects.all()
  return render(request, 'birds/index.html', { 'birds': birds })

def birds_detail(request, bird_id):
  bird = Bird.objects.get(id=bird_id)
    # First, create a list of the toy ids that the cat DOES have
  id_list = bird.houses.all().values_list('id')
  # Now we can query for toys whose ids are not in the list using exclude
  houses_bird_doesnt_have = House.objects.exclude(id__in=id_list)
  feeding_form = FeedingForm()
  return render(request, 'birds/detail.html', {
    'bird': bird, 'feeding_form': feeding_form,
    # Add the houses to be displayed
    'houses': houses_bird_doesnt_have
    })

def add_feeding(request, bird_id):
  # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the bird_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.bird_id = bird_id
    new_feeding.save()
  return redirect('detail', bird_id=bird_id)


class HouseList(ListView):
  model = House


class HouseDetail(DetailView):
  model = House


class HouseCreate(CreateView):
  model = House
  fields = '__all__'


class HouseUpdate(UpdateView):
  model = House
  fields = ['name', 'color']


class HouseDelete(DeleteView):
  model = House
  success_url = '/houses/'

def assoc_house(request, bird_id, house_id):
  # Note that you can pass a house's id instead of the whole house object
  Bird.objects.get(id=bird_id).houses.add(house_id)
  return redirect('detail', bird_id=bird_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Socal Bird Collector</h1>
<hr>
<p>Hire the Socal Bird Collector!</p>
<footer>All Rights Reserved, &copy; 2023 Socal Bird Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Socal Bird Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Socal Bird Collector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'houses_create' %}">Add a House</a></li>
					<li><a href="{% url 'houses_index' %}">View All Houses</a></li>
                    <li><a href="{% url 'birds_create' %}">Add a Bird</a></li>
                    <li><a href="{% url 'index' %}">View All My Birds</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2023 Socal Bird Collector &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/birds/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Bird Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ bird.name }}</span>
                <p>Breed: {{ bird.breed }}</p>
                <p>Description: {{ bird.description|linebreaks }}</p>
                {% if bird.age > 0 %}
                <p>Age: {{ bird.age }}</p>
                {% else %}
                <p>Age: Kitten</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'birds_update' bird.id %}">Edit</a>
                <a href="{% url 'birds_delete' bird.id %}">Delete</a>
            </div>
        </div>

        {% for photo in bird.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}

        <form action="{% url 'add_photo' bird.id %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br>
            <button type="submit" class="btn">Upload Photo</button>
        </form>


    </div>
    <!-- New Markup Below -->
    <div class="col s6">
        <form action="{% url 'add_feeding' bird.id %}" method="POST">
            {% csrf_token %}
            <!-- Render the inputs -->
            {{ feeding_form.as_p }}
            <input type="submit" class="btn" value="Add Feeding">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in bird.feeding_set.all %}
                <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- New Markup Above -->
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ bird.name }}'s Houses</h3>
        {% if bird.houses.count %}
        {% for house in bird.houses.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ house.color }}">{{ house.color }}</span> {{ house.name }}
                </span>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No Houses 😿</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Houses</h3>
        {% if houses.count %}
        {% for house in houses.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ house.color }}">{{ house.color }}</span> {{ house.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_house' bird.id house.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{bird.name}} Already Has All Houses Available</h5>
        {% endif %}
    </div>
</div>

<script>
    const dateEl = document.getElementById('id_date');
    // M is Materialize's global variable
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    // add additional JS to initialize select below
    const selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/birds/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Bird List</h1>

{% for bird in birds %}
<div class="card">
    <a href="{% url 'detail' bird.id %}">
        <div class="card-content">
            <span class="card-title">{{ bird.name }}</span>
            <p>Breed: {{ bird.breed }}</p>
            <p>Description: {{ bird.description|linebreaks }}</p>
            {% if bird.age > 0 %}
            <p>Age: {{ bird.age }}</p>
            {% else %}
            <p>Age: Birdie</p>
            {% endif %}
        </div>
        <!-- Add the following one as well -->
    </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}



{% block content %}
<h1>Home</h1>

{% endblock content %}

main_app/templates/main_app/bird_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Bird</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' bird.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/bird_form.html
{% extends 'base.html' %}



{% block content %}


<!-- two variables from the update, they have same values
object - current instance 
lowercase model name - current instance 

in our case. Our two variables are 

object 
bird -->

<!-- object will have a value of None when we are creating something -->

{% if object %}
	<h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
	<h1>Add Bird</h1>
{% endif %}
	



<!-- Leave our action blank, it will make a post request to the same 
url used to display it, in our case birds/create -->
<form action="" method="POST">
	<!-- we need the csrf token in every form for security 
	purposes -->
	{% csrf_token %} 
	<table>
		<!-- We get the form variable from our CBV (BirdsCreate view function) -->
		{{ form.as_table }}
	</table>
	<button type="submit" class="btn">Submit</button>
</form>
	
{% endblock content %}
	

main_app/templates/main_app/house_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete House</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'houses_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/house_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>House Details</h1>

<div class="row">
    <div class="col s6 col-offset-3">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ house.name }}</span>
                <p>Color: {{ house.color }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'houses_update' house.id %}">Edit</a>
                <a href="{% url 'houses_delete' house.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/house_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add House</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/house_list.html
{% extends 'base.html' %}
{% block content %}

<h1>House List</h1>

you get two variables in the list page (index page)

<!-- <model_name>_list 
object_list -->

<!-- house_list 
object_list -->

{% for house in house_list %}
<a href="{% url 'houses_detail' house.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ house.name }}</span>
            <p>Color: {{ house.color }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}